name: Build UTM Snapshot Manager

on:
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the app
        run: |
          xcodebuild -project "UTM Snapshot Manager.xcodeproj" \
          -scheme "UTM Snapshot Manager" \
          -configuration Release \
          clean build \
          CONFIGURATION_BUILD_DIR="$(pwd)/build"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UTM-Snapshot-Manager-App
          path: build/UTM Snapshot Manager.app